services:
  nats-location-1:
    container_name: nats-location-1
    image: nats
    ports:
      - "4223:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    networks:
      - nats-net
    command: ">
      -p 4223
      --http-port 8222
      --cluster_name location
      --cluster_listen 0.0.0.0:6222
      --routes nats://nats-location-2:6222,nats://nats-location-3:6222
      "

  nats-location-2:
    container_name: nats-location-2
    image: nats
    ports:
      - "4224:4222" # client port
      - "6223:6222" # cluster port
      - "8223:8222" # monitoring port
    networks:
      - nats-net
    command: ">
      -p 4224
      --http-port 8222
      --cluster_name location
      --cluster_listen 0.0.0.0:6222
      --routes nats://nats-location-1:6222,nats://nats-location-3:6222
      "

  nats-location-3:
    container_name: nats-location-3
    image: nats
    ports:
      - "4225:4222" # client port
      - "6224:6222" # cluster port
      - "8224:8222" # monitoring port
    networks:
      - nats-net
    command: ">
      -p 4225
      --http-port 8222
      --cluster_name location
      --cluster_listen 0.0.0.0:6222
      --routes nats://nats-location-1:6222,nats://nats-location-2:6222
      "

networks:
  nats-net:
    driver: bridge